# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mailo Arsac
email: me@mailoarsac.com
description: >- # this means to ignore newlines until "baseurl:"
  Proven senior developer with experience at each level of the development process.
  Adept at complex problem solving and communicating solutions as well as providing mentorship to junior team members.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mailoarsac.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mailo_arsac
github_username:  arsac
linkedin_username: mailoarsac
location: Portland, OR

analytics: "UA-50836637-1"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - package.json
 - webpack.config.js
 - poatcss.config.js
 - yarn-error.log
 - yarn.lock
 - loaders
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/

defaults:
  - scope:
      path: "_src/img"
    values:
      image: true